export enum CampaignStatus {
  ACTIVE = "ACTIVE",
  PAUSED = "PAUSED",
  ENDED = "ENDED",
}

export enum CampaignType {
  VISIBILITY = "VISIBILITY",
  CONSULTANT = "CONSULTANT",
  SELLER = "SELLER",
  SALESMAN = "SALESMAN",
}

export enum SalesTrackingMethod {
  REF_LINK = "REF_LINK",
  COUPON_CODE = "COUPON_CODE",
}

export enum Deliverable {
  PROMOTIONAL_VIDEO = "PROMOTIONAL_VIDEO",
  SCRIPT = "SCRIPT",
  CONTENT_PLAN = "CONTENT_PLAN",
  WEEKLY_REPORT = "WEEKLY_REPORT",
  LIVE_SESSION = "LIVE_SESSION",
  PRODUCT_REVIEW = "PRODUCT_REVIEW",
  INSTAGRAM_POST = "INSTAGRAM_POST",
  TIKTOK_VIDEO = "TIKTOK_VIDEO",
  CUSTOM = "CUSTOM",
}

export enum MeetingPlan {
  ONE_TIME = "ONE_TIME",
  WEEKLY = "WEEKLY",
  BIWEEKLY = "BIWEEKLY",
  CUSTOM = "CUSTOM",
}

export enum PromoterCampaignStatus {
  ONGOING = "ONGOING",
  AWAITING_REVIEW = "AWAITING_REVIEW",
  COMPLETED = "COMPLETED",
  PAUSED = "PAUSED",
}
